//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Assets/Scripts/WheelchairControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Assets/Scripts/WheelchairControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @WheelchairControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @WheelchairControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""WheelchairControls"",
    ""maps"": [
        {
            ""name"": ""LeftWheel"",
            ""id"": ""371222fd-6a6f-4bb3-a206-f961fb007725"",
            ""actions"": [
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""a964ad45-070b-49d9-bb0c-7b7a0cb6059f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""669e09b1-0c29-4a2b-8e57-eb5637a46872"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightWheel"",
            ""id"": ""3ecbcb08-e368-42cb-9ca6-5d738cd4a96c"",
            ""actions"": [
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""89ba0665-be3d-4ae0-b31a-1007d343d5ac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ed3c3f91-b855-4cc4-92f5-25e56227cec6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Scroll"",
            ""id"": ""cb58ffab-e9fb-4f1b-947f-2b34af835565"",
            ""actions"": [
                {
                    ""name"": ""PushChair"",
                    ""type"": ""Value"",
                    ""id"": ""fa473c71-41f1-4d25-8116-11a9ec8530e7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ff8eb4c4-b95f-4ce9-a8c4-5c6fc87e01fb"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushChair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Look"",
            ""id"": ""3b813bba-fcb6-4846-a5fa-9f78867e62d5"",
            ""actions"": [
                {
                    ""name"": ""LookInput"",
                    ""type"": ""Value"",
                    ""id"": ""d5053802-184a-4f5d-99f3-6db084aadabd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d66f1d6b-94be-428d-87c7-5c9b4425dba6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d881b9b3-8a96-4a38-812a-3d36c70d2a98"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LeftWheel
        m_LeftWheel = asset.FindActionMap("LeftWheel", throwIfNotFound: true);
        m_LeftWheel_MoveRight = m_LeftWheel.FindAction("MoveRight", throwIfNotFound: true);
        // RightWheel
        m_RightWheel = asset.FindActionMap("RightWheel", throwIfNotFound: true);
        m_RightWheel_MoveLeft = m_RightWheel.FindAction("MoveLeft", throwIfNotFound: true);
        // Scroll
        m_Scroll = asset.FindActionMap("Scroll", throwIfNotFound: true);
        m_Scroll_PushChair = m_Scroll.FindAction("PushChair", throwIfNotFound: true);
        // Look
        m_Look = asset.FindActionMap("Look", throwIfNotFound: true);
        m_Look_LookInput = m_Look.FindAction("LookInput", throwIfNotFound: true);
    }

    ~@WheelchairControls()
    {
        UnityEngine.Debug.Assert(!m_LeftWheel.enabled, "This will cause a leak and performance issues, WheelchairControls.LeftWheel.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_RightWheel.enabled, "This will cause a leak and performance issues, WheelchairControls.RightWheel.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Scroll.enabled, "This will cause a leak and performance issues, WheelchairControls.Scroll.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Look.enabled, "This will cause a leak and performance issues, WheelchairControls.Look.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LeftWheel
    private readonly InputActionMap m_LeftWheel;
    private List<ILeftWheelActions> m_LeftWheelActionsCallbackInterfaces = new List<ILeftWheelActions>();
    private readonly InputAction m_LeftWheel_MoveRight;
    /// <summary>
    /// Provides access to input actions defined in input action map "LeftWheel".
    /// </summary>
    public struct LeftWheelActions
    {
        private @WheelchairControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public LeftWheelActions(@WheelchairControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "LeftWheel/MoveRight".
        /// </summary>
        public InputAction @MoveRight => m_Wrapper.m_LeftWheel_MoveRight;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_LeftWheel; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="LeftWheelActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(LeftWheelActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="LeftWheelActions" />
        public void AddCallbacks(ILeftWheelActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftWheelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftWheelActionsCallbackInterfaces.Add(instance);
            @MoveRight.started += instance.OnMoveRight;
            @MoveRight.performed += instance.OnMoveRight;
            @MoveRight.canceled += instance.OnMoveRight;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="LeftWheelActions" />
        private void UnregisterCallbacks(ILeftWheelActions instance)
        {
            @MoveRight.started -= instance.OnMoveRight;
            @MoveRight.performed -= instance.OnMoveRight;
            @MoveRight.canceled -= instance.OnMoveRight;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="LeftWheelActions.UnregisterCallbacks(ILeftWheelActions)" />.
        /// </summary>
        /// <seealso cref="LeftWheelActions.UnregisterCallbacks(ILeftWheelActions)" />
        public void RemoveCallbacks(ILeftWheelActions instance)
        {
            if (m_Wrapper.m_LeftWheelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="LeftWheelActions.AddCallbacks(ILeftWheelActions)" />
        /// <seealso cref="LeftWheelActions.RemoveCallbacks(ILeftWheelActions)" />
        /// <seealso cref="LeftWheelActions.UnregisterCallbacks(ILeftWheelActions)" />
        public void SetCallbacks(ILeftWheelActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftWheelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftWheelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="LeftWheelActions" /> instance referencing this action map.
    /// </summary>
    public LeftWheelActions @LeftWheel => new LeftWheelActions(this);

    // RightWheel
    private readonly InputActionMap m_RightWheel;
    private List<IRightWheelActions> m_RightWheelActionsCallbackInterfaces = new List<IRightWheelActions>();
    private readonly InputAction m_RightWheel_MoveLeft;
    /// <summary>
    /// Provides access to input actions defined in input action map "RightWheel".
    /// </summary>
    public struct RightWheelActions
    {
        private @WheelchairControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public RightWheelActions(@WheelchairControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "RightWheel/MoveLeft".
        /// </summary>
        public InputAction @MoveLeft => m_Wrapper.m_RightWheel_MoveLeft;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_RightWheel; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="RightWheelActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(RightWheelActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="RightWheelActions" />
        public void AddCallbacks(IRightWheelActions instance)
        {
            if (instance == null || m_Wrapper.m_RightWheelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightWheelActionsCallbackInterfaces.Add(instance);
            @MoveLeft.started += instance.OnMoveLeft;
            @MoveLeft.performed += instance.OnMoveLeft;
            @MoveLeft.canceled += instance.OnMoveLeft;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="RightWheelActions" />
        private void UnregisterCallbacks(IRightWheelActions instance)
        {
            @MoveLeft.started -= instance.OnMoveLeft;
            @MoveLeft.performed -= instance.OnMoveLeft;
            @MoveLeft.canceled -= instance.OnMoveLeft;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RightWheelActions.UnregisterCallbacks(IRightWheelActions)" />.
        /// </summary>
        /// <seealso cref="RightWheelActions.UnregisterCallbacks(IRightWheelActions)" />
        public void RemoveCallbacks(IRightWheelActions instance)
        {
            if (m_Wrapper.m_RightWheelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="RightWheelActions.AddCallbacks(IRightWheelActions)" />
        /// <seealso cref="RightWheelActions.RemoveCallbacks(IRightWheelActions)" />
        /// <seealso cref="RightWheelActions.UnregisterCallbacks(IRightWheelActions)" />
        public void SetCallbacks(IRightWheelActions instance)
        {
            foreach (var item in m_Wrapper.m_RightWheelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightWheelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="RightWheelActions" /> instance referencing this action map.
    /// </summary>
    public RightWheelActions @RightWheel => new RightWheelActions(this);

    // Scroll
    private readonly InputActionMap m_Scroll;
    private List<IScrollActions> m_ScrollActionsCallbackInterfaces = new List<IScrollActions>();
    private readonly InputAction m_Scroll_PushChair;
    /// <summary>
    /// Provides access to input actions defined in input action map "Scroll".
    /// </summary>
    public struct ScrollActions
    {
        private @WheelchairControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ScrollActions(@WheelchairControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Scroll/PushChair".
        /// </summary>
        public InputAction @PushChair => m_Wrapper.m_Scroll_PushChair;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Scroll; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ScrollActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ScrollActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ScrollActions" />
        public void AddCallbacks(IScrollActions instance)
        {
            if (instance == null || m_Wrapper.m_ScrollActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ScrollActionsCallbackInterfaces.Add(instance);
            @PushChair.started += instance.OnPushChair;
            @PushChair.performed += instance.OnPushChair;
            @PushChair.canceled += instance.OnPushChair;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ScrollActions" />
        private void UnregisterCallbacks(IScrollActions instance)
        {
            @PushChair.started -= instance.OnPushChair;
            @PushChair.performed -= instance.OnPushChair;
            @PushChair.canceled -= instance.OnPushChair;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ScrollActions.UnregisterCallbacks(IScrollActions)" />.
        /// </summary>
        /// <seealso cref="ScrollActions.UnregisterCallbacks(IScrollActions)" />
        public void RemoveCallbacks(IScrollActions instance)
        {
            if (m_Wrapper.m_ScrollActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ScrollActions.AddCallbacks(IScrollActions)" />
        /// <seealso cref="ScrollActions.RemoveCallbacks(IScrollActions)" />
        /// <seealso cref="ScrollActions.UnregisterCallbacks(IScrollActions)" />
        public void SetCallbacks(IScrollActions instance)
        {
            foreach (var item in m_Wrapper.m_ScrollActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ScrollActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ScrollActions" /> instance referencing this action map.
    /// </summary>
    public ScrollActions @Scroll => new ScrollActions(this);

    // Look
    private readonly InputActionMap m_Look;
    private List<ILookActions> m_LookActionsCallbackInterfaces = new List<ILookActions>();
    private readonly InputAction m_Look_LookInput;
    /// <summary>
    /// Provides access to input actions defined in input action map "Look".
    /// </summary>
    public struct LookActions
    {
        private @WheelchairControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public LookActions(@WheelchairControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Look/LookInput".
        /// </summary>
        public InputAction @LookInput => m_Wrapper.m_Look_LookInput;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Look; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="LookActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(LookActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="LookActions" />
        public void AddCallbacks(ILookActions instance)
        {
            if (instance == null || m_Wrapper.m_LookActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LookActionsCallbackInterfaces.Add(instance);
            @LookInput.started += instance.OnLookInput;
            @LookInput.performed += instance.OnLookInput;
            @LookInput.canceled += instance.OnLookInput;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="LookActions" />
        private void UnregisterCallbacks(ILookActions instance)
        {
            @LookInput.started -= instance.OnLookInput;
            @LookInput.performed -= instance.OnLookInput;
            @LookInput.canceled -= instance.OnLookInput;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="LookActions.UnregisterCallbacks(ILookActions)" />.
        /// </summary>
        /// <seealso cref="LookActions.UnregisterCallbacks(ILookActions)" />
        public void RemoveCallbacks(ILookActions instance)
        {
            if (m_Wrapper.m_LookActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="LookActions.AddCallbacks(ILookActions)" />
        /// <seealso cref="LookActions.RemoveCallbacks(ILookActions)" />
        /// <seealso cref="LookActions.UnregisterCallbacks(ILookActions)" />
        public void SetCallbacks(ILookActions instance)
        {
            foreach (var item in m_Wrapper.m_LookActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LookActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="LookActions" /> instance referencing this action map.
    /// </summary>
    public LookActions @Look => new LookActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "LeftWheel" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="LeftWheelActions.AddCallbacks(ILeftWheelActions)" />
    /// <seealso cref="LeftWheelActions.RemoveCallbacks(ILeftWheelActions)" />
    public interface ILeftWheelActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveRight(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "RightWheel" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="RightWheelActions.AddCallbacks(IRightWheelActions)" />
    /// <seealso cref="RightWheelActions.RemoveCallbacks(IRightWheelActions)" />
    public interface IRightWheelActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveLeft(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Scroll" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ScrollActions.AddCallbacks(IScrollActions)" />
    /// <seealso cref="ScrollActions.RemoveCallbacks(IScrollActions)" />
    public interface IScrollActions
    {
        /// <summary>
        /// Method invoked when associated input action "PushChair" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPushChair(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Look" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="LookActions.AddCallbacks(ILookActions)" />
    /// <seealso cref="LookActions.RemoveCallbacks(ILookActions)" />
    public interface ILookActions
    {
        /// <summary>
        /// Method invoked when associated input action "LookInput" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLookInput(InputAction.CallbackContext context);
    }
}
